
Skip to content
Pull requests
Issues
Marketplace
Explore
@M0TRIX
M0TRIX /
Wallapop
Public

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights

    Settings

Wallapop/.github/workflows/ios.yml
@M0TRIX
M0TRIX Update ios.yml
Latest commit 3a1c2ca 20 days ago
History
1 contributor
20 lines (15 sloc) 435 Bytes
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app

    - name: Build and test
      run: xcodebuild \test \-project CountryList-home-assignment/RestCountries/RestCountries.xcodeproj -scheme RestCountries -destination 'platform=iOS Simulator,name=iPhone 13'

    © 2022 GitHub, Inc.

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

Loading complete
